name: todoey
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  image_picker: ^0.8.6+4
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  persistent_bottom_nav_bar: ^5.0.2
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
